### ISSUE TITLE
YahooXL stopped working

### ISSUE THREAD

**Issue by stagnoman** [dshe/YahooXL#1]
Hi dshe, hope u are well.
Apparently, yahooxl stopped working. I use excel 2016 64bit, during last few days the returned value is always ~.

![err](https://user-images.githubusercontent.com/2866789/233351957-dd12388f-6688-4411-a313-2114dc046a0e.png)

many thks

**Comment by stagnoman** [comment]
yahoo servers down

**Comment by stagnoman** [comment]
Hi there,
it stopped working since the beginning of May.
I think the problem is due to yahoo cookies. 
Let me know if you can help.
Ciaoo

**Comment by dshe** [comment]
Please try the new version.

**Comment by dshe** [comment]
Please try the new version.
