### ISSUE TITLE
Dependency YahooQuotesApi should be updated from version 5.5.1 to 5.5.5

### ISSUE THREAD

**Issue by izzeww** [dshe/YahooXL#2]
Otherwise it doesn't work for europeans. In YahooXL.csproj from `<PackageReference Include="YahooQuotesApi" Version="5.5.1" />` to `<PackageReference Include="YahooQuotesApi" Version="5.5.5" />`. Did a pull request for this, don't really know why I did an issue too.

**Comment by dshe** [comment]
@izzeww Thank you!
