### ISSUE TITLE
Where is the file YahooXL-AddIn64-packed.xll?

### ISSUE THREAD

**Issue by ks2018ks** [dshe/YahooXL#4]
Instructions here https://github.com/dshe/YahooXL say:

"Copy "YahooXL-AddIn64-packed.xll" (64 bit) or "YahooXL-AddIn-packed.xll" (32 bit) from GitHub Releases to a folder."

But "YahooXL-AddIn64-packed.xll" is apparently in the repository, unless I'm missing something

**Comment by dshe** [comment]
Click on "Releases", which is located on the right column of the main repository page.
